### ISSUE TITLE
TPDO change-of-state mechanism in canopend

### ISSUE THREAD

**Issue by MaroZz** [CANopenNode/CANopenLinux#19]
It seems like the change-of-state mechanism isn't working in canopend
Please correct me if I'm wrong; perhaps it's working as intended

Initially, I thought that every entry in the OD supported this, and i only needed to correctly configure the TPDO mapping for the value to be transmitted.
However, it only transmits if the event timer is not zero (another mechanism working in this case)
when i change the value with cocomm it's not being transmitted.

As the documentation states it's an "application event," perhaps it must be triggered in something like CO_application.c for every OD entry?

**Comment by CANopenNode** [comment]
Change of state in Linux is working as intended. In CANopenNode v4 it has to be handled by application, as shown in demo/CO_application.c. I think, OD_requestTPDO() may be quite useful functionality and offers many options.

Instead of `static int32_t value_old`, you can also use setter function, which verifies, if value is changing. Etc.

Please note, there may be a problem, if you have many TPDOs triggered on change of state. There may be critical situations, where all TPDOs on network triggers at once and that may overload the network. Properly configured synchronous PDOs may have more bus load in average, but are much more deterministic.
